### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by 3DCoded** [playi/WonderPy#31]
I am using MacOS 11.1 and Python 3.9.1 64-bit. When I try to import `WonderPy`, I get an error: 
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import WonderPy
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/WonderPy/__init__.py", line 1, in <module>
    from . import core        # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/WonderPy/core/__init__.py", line 1, in <module>
    from wwCommands  import WWCommands  # noqa
ModuleNotFoundError: No module named 'wwCommands'
```
Is there a way to use this package in Python 3?

**Comment by kevincowan** [comment]
I got the same WWCommands error on Python 3 with MacOS 11.1

I get this error on Python 2.7 - how did you get past it? @smattar2020

` ➜ python tutorial/01_hello_world.py
Traceback (most recent call last):
  File "tutorial/01_hello_world.py", line 76, in <module>
    WonderPy.core.wwMain.start(MyClass())
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/WonderPy/core/wwMain.py", line 6, in start
    WonderPy.core.wwBTLEMgr.WWBTLEManager(delegate_instance, arguments).run()
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/WonderPy/core/wwBTLEMgr.py", line 70, in __init__
    self.ble = Adafruit_BluefruitLE.get_provider()
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/Adafruit_BluefruitLE/platform.py", line 42, in get_provider
    from .corebluetooth.provider import CoreBluetoothProvider
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/Adafruit_BluefruitLE/corebluetooth/provider.py", line 39, in <module>
    from .objc_helpers import uuid_to_cbuuid
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/Adafruit_BluefruitLE/corebluetooth/objc_helpers.py", line 30, in <module>
    bundle_path=objc.pathForFramework(u'/System/Library/Frameworks/IOBluetooth.framework/Versions/A/Frameworks/CoreBluetooth.framework'))
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/objc/_dyld.py", line 122, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/objc/_dyld.py", line 117, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Users/kevincowan/Documents/Dash/WonderPyExamples/venv/lib/python2.7/site-packages/objc/_dyld.py", line 88, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreBluetooth could not be found`

**Comment by 3DCoded** [comment]
I think I enabled Bluetooth for Python or whatever Code IDE you may be using. I think the Dash/Dot/Cue has to be on when you import it.

**Comment by kevincowan** [comment]
That didn't help @smattar2020 I'd really love to know how you got this to work on Python 2.7 on MacOS 11.1 - thanks!

**Comment by 3DCoded** [comment]
I did it a while ago and am not sure I remember how to do it. This issue is for making it work on Python3, not Python 2.

**Comment by 3DCoded** [comment]
You may have to install CoreBluetooth somehow

**Comment by 3DCoded** [comment]
eg.  at https://pypi.org/project/pyobjc-framework-CoreBluetooth/

**Comment by kevincowan** [comment]
I tried that and it didn't work

I know you are trying to get Python3 working - I can't make it work on Python 2.7 on 11.1

**Comment by 3DCoded** [comment]
I have uninstalled Python 2 recently because it was deprecated since December 2020 and because it was crashing my Mac. I think if you are trying to get it to work on Python 2 on macOS Big Sur, you should open your own issue for that.

**Comment by kevincowan** [comment]
Agreed - thanks for your help.  We really need it work on Python 3

**Comment by kevincowan** [comment]
I've emailed their support to ask about Python 3 support - we need this

**Comment by mewmix** [comment]
I ported some work by the github community to use bleak backend instead of pygatt, and I have tested on my mac m1 and windows machine for anyone still looking. 

https://github.com/mewmix/bleak-dash

**Comment by kevincowan** [comment]
@mewmix You are a hero! Can't wait to try this!

Thanks

**Comment by axlan** [comment]
I created  a more direct port with additional functionality that's also cross platform:
https://github.com/axlan/WonderPy
