### ISSUE TITLE
Port to Linux

### ISSUE THREAD

**Issue by elenzil** [playi/WonderPy#5]
this _may_ function with the current AdaFruit library, we haven't had a chance to test.

**Comment by hawflakes** [comment]
I'd be happy to try it out if you can drop in a `libWWHAL.so`

**Comment by elenzil** [comment]
just saw your comment, @hawflakes . apologies !
i'll see what i can do.

**Comment by liuwencong** [comment]
> this _may_ function with the current AdaFruit library, we haven't had a chance to test.

Current AdaFruit library doesn't work, I've tried on RaspBerry.  The AdaFruit library bluez_dbus also needs modification to add manufacturerData property similar as that done in corebluetooth.

trace as following:
(venv27) pi@raspberrypi:~ $ sudo python venv27/WonderPyExamples-master/tutorial/01_hello_world.py
Disconnecting any connected robots..
Searching for robot types: (all) with names: (any).
matching robots: 0  non-matching robots: 0 .................        Traceback (most recent call last):
  File "venv27/WonderPyExamples-master/tutorial/01_hello_world.py", line 75, in <module>
    WonderPy.core.wwMain.start(MyClass())
  File "/home/pi/venv27/WonderPy-master/WonderPy/core/wwMain.py", line 6, in start
    WonderPy.core.wwBTLEMgr.WWBTLEManager(delegate_instance, arguments).run()
  File "/home/pi/venv27/WonderPy-master/WonderPy/core/wwBTLEMgr.py", line 381, in run
    self.ble.run_mainloop_with(self.scan_and_connect)
  File "/home/pi/venv27/Adafruit_Python_BluefruitLE-master/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
    raise_(self._exception[1], None, self._exception[2])
  File "/home/pi/venv27/Adafruit_Python_BluefruitLE-master/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
    self._return_code = target()
  File "/home/pi/venv27/WonderPy-master/WonderPy/core/wwBTLEMgr.py", line 153, in scan_and_connect
    rob = WWRobot(d)
  File "/home/pi/venv27/WonderPy-master/WonderPy/core/wwRobot.py", line 30, in __init__
    self.parseManufacturerData(btleDevice.manufacturerData)
AttributeError: **'BluezDevice' object has no attribute 'manufacturerData'**

**Comment by liuwencong** [comment]
@elenzil how about implement the functions packets2Json and json2Packets (which is currently in libWWHAL.dylib) with Python to make WonderPy not rely on operating system?  Thanks!

**Comment by paulolc** [comment]
It seems you've made some progress @liuwencong... Was it using libWWHAL.so? If so, where can I find it? I'm also trying to get WonderPy working on a Raspberry Pi but I'm still stuck on #18 unable to install WonderPy.

**Comment by elenzil** [comment]
Hi All -
many apologies for being so inactive on this project.
i don't foresee myself or other folks at Wonder Workshop being able to contribute much time in the near future, either.  :/

but i can provide a few details.

responding to comments in #18, which i'm closing as a dupe of #5:

> From what I see, the PyObjC is used to load the native MacOS dynamic library binary "libWWHAL.dylib"

good guess, but slightly off.
PyObjC is a dependency of the AdaFruit bluetooth low energy package,
where it is used to bind to Apple's BTLE services.
I believe it is possible to use the AdaFruit btle package on Linux, but i haven't done it myself.

libWWHAL.dylib is loaded via the regular python library loading methods.
however it is definitely compiled for MacOS, so isn't much good on Linux.
I'll try to carve out some time to compile it for Linux. #5 .

**Comment by paulolc** [comment]
> I'll try to carve out some time to compile it for Linux. #5 .
Any luck @elenzil? I could try to compile libWWHAL for Linux myself, if only I had the source ;)

**Comment by euivmar** [comment]
My 2 cents contribution: 

https://github.com/adafruit/Adafruit_Python_BluefruitLE

Here you can find the Adafruit_Python_BluefruitLE library for compilation in Linux (including Rasbian).

Also, I have tested this unnofficial git repository and it works in ubuntu! 

https://github.com/IlyaSukhanov/morseapi

Maybe, it can be used to improve the official version.
